# @Author       : Ruopeng Gao
# @Description  : Config for training DanceTrack.

GIT_VERSION:

MODE: train
CONFIG_PATH:
VISUALIZE: False
AVAILABLE_GPUS: 0,1,2,3,4,5,6,7
DEVICE: cuda
OUTPUTS_DIR: ./outputs/pycharm/
USE_DISTRIBUTED: False
USE_CHECKPOINT: False
CHECKPOINT_LEVEL: 2               # gradient checkpoint level.
                                  # As the number increases (from 1 to 4), the memory cost increases.
                                  # We have deleted many comments in this official code simplicity,
                                  # if you have any questions, feel free to contact with the author.
RESUME:
RESUME_SCHEDULER: True
MULTI_CHECKPOINT: False

# About submit
SUBMIT_DIR:
SUBMIT_MODEL:
SUBMIT_DATA_SPLIT: test
DET_SCORE_THRESH: 0.5
TRACK_SCORE_THRESH: 0.5
RESULT_SCORE_THRESH: 0.5
MISS_TOLERANCE: 15
USE_MOTION: False
MOTION_MIN_LENGTH: 3
MOTION_MAX_LENGTH: 5
MOTION_LAMBDA: 0.5

# About Evaluation
EVAL_DIR:
EVAL_MODE: specific               # specific/continue
EVAL_MODEL:
EVAL_PORT:
EVAL_THREADS: 1
EVAL_DATA_SPLIT: val

# About data processing
DATASET: MOT17
USE_MOTSYNTH:
USE_CROWDHUMAN: True
MOTSYNTH_RATE:
DATA_ROOT:
DATA_PATH:
NUM_WORKERS: 4
BATCH_SIZE: 1
ACCUMULATION_STEPS: 1
COCO_SIZE: False
OVERFLOW_BBOX: False
REVERSE_CLIP: 0.0

# About model
BACKBONE: resnet50
HIDDEN_DIM: 256
FFN_DIM: 2048
NUM_FEATURE_LEVELS: 4
NUM_HEADS: 8
NUM_ENC_POINTS: 4
NUM_DEC_POINTS: 4
NUM_ENC_LAYERS: 6
NUM_DEC_LAYERS: 6
MERGE_DET_TRACK_LAYER: 1
ACTIVATION: ReLU
RETURN_INTER_DEC: True
EXTRA_TRACK_ATTN: False
AUX_LOSS: True
USE_DAB: True
UPDATE_THRESH: 0.5
LONG_MEMORY_LAMBDA: 0.01
# Pretrain model
PRETRAINED_MODEL: dab_deformable_detr.pth

# Sampling setting
SAMPLE_STEPS: [60, 100]
SAMPLE_LENGTHS: [2, 3, 4]
SAMPLE_MODES: [random_interval]
SAMPLE_INTERVALS: [10]
SAMPLE_MOT17_JOIN: 0

# Training setting
SEED: 42
EPOCHS: 130
ONLY_TRAIN_QUERY_UPDATER_AFTER: 130
DROPOUT: 0.0
NUM_DET_QUERIES: 300
# training augmentation
TP_DROP_RATE: 0.0
FP_INSERT_RATE: 0.0
LR: 2.0e-4
LR_BACKBONE: 2.0e-5
LR_POINTS: 2.0e-5
WEIGHT_DECAY: 0.0001
CLIP_MAX_NORM: 0.1
LR_SCHEDULER: MultiStep
LR_DROP_RATE: 0.1
LR_DROP_MILESTONES: [120]
# DETR matcher
MATCH_COST_CLASS: 2
MATCH_COST_BBOX: 5
MATCH_COST_GIOU: 2
# DETR loss
LOSS_WEIGHT_FOCAL: 2
LOSS_WEIGHT_L1: 5
LOSS_WEIGHT_GIOU: 2
# Aux Loss Weight
AUX_LOSS_WEIGHT: [1.0, 1.0, 1.0, 1.0, 1.0]
