# @Author       : Ruopeng Gao
# @Date         : 2022/8/30
# @Description  : Config for training BDD100K.

GIT_VERSION:

MODE: train
CONFIG_PATH:
VISUALIZE: False
AVAILABLE_GPUS: 0,1,2,3,4,5,6,7
DEVICE: cuda
OUTPUTS_DIR: ./outputs/pycharm/
USE_DISTRIBUTED: False
USE_CHECKPOINT: False
CHECKPOINT_LEVEL: 2
RESUME:
RESUME_SCHEDULER: False
MULTI_CHECKPOINT: False

SUBMIT_DIR:
SUBMIT_MODEL:
SUBMIT_DATA_SPLIT: val
DET_SCORE_THRESH: 0.5
TRACK_SCORE_THRESH: 0.5
RESULT_SCORE_THRESH: 0.5
MISS_TOLERANCE: 10
USE_MOTION: False
MOTION_MIN_LENGTH: 3
MOTION_MAX_LENGTH: 5
MOTION_LAMBDA: 0.5

EVAL_DIR:
EVAL_MODE: specific
EVAL_MODEL:
EVAL_PORT:
EVAL_THREADS: 1
EVAL_DATA_SPLIT: val

DATASET: BDD100K
DATA_ROOT: /data3/gaoruopeng/DatasetsForMeMOTR/
DATA_PATH:
NUM_WORKERS: 8
BATCH_SIZE: 1
ACCUMULATION_STEPS: 1

BACKBONE: resnet50
HIDDEN_DIM: 256
FFN_DIM: 2048
NUM_FEATURE_LEVELS: 4
NUM_HEADS: 8
NUM_ENC_POINTS: 4
NUM_DEC_POINTS: 4
NUM_ENC_LAYERS: 6
NUM_DEC_LAYERS: 6
MERGE_DET_TRACK_LAYER: 1
ACTIVATION: ReLU
RETURN_INTER_DEC: True
EXTRA_TRACK_ATTN: False
AUX_LOSS: True
USE_DAB: True
UPDATE_THRESH: 0.5
LONG_MEMORY_LAMBDA: 0.01

PRETRAINED_MODEL: dab_deformable_detr.pth

SAMPLE_STEPS: [6, 10]
SAMPLE_LENGTHS: [2, 3, 4]
SAMPLE_MODES: [random_interval]
SAMPLE_INTERVALS: [4, 4, 4]

SEED: 42
EPOCHS: 13    # or 14, is OK.
ONLY_TRAIN_QUERY_UPDATER_AFTER: 1000
DROPOUT: 0.0
NUM_DET_QUERIES: 300
TP_DROP_RATE: 0.0
FP_INSERT_RATE: 0.0
LR: 2.0e-4
LR_BACKBONE: 2.0e-5
LR_POINTS: 1.0e-5
WEIGHT_DECAY: 0.0002
CLIP_MAX_NORM: 0.1
LR_SCHEDULER: MultiStep
LR_DROP_RATE: 0.1
LR_DROP_MILESTONES: [12]
MATCH_COST_CLASS: 2
MATCH_COST_BBOX: 5
MATCH_COST_GIOU: 2
LOSS_WEIGHT_FOCAL: 2
LOSS_WEIGHT_L1: 5
LOSS_WEIGHT_GIOU: 2
# Aux Loss Weight
AUX_LOSS_WEIGHT: [1.0, 1.0, 1.0, 1.0, 1.0]
